name: Main

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0, 8.1]
    name: PHP ${{ matrix.php }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            coverage: none
            tools: php-cs-fixer:3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run PHP CS Fixer
        run: php-cs-fixer fix --diff --dry-run

      - name: Install
        uses: "ramsey/composer-install@v2"

      - name: Run tests
        run: ./vendor/bin/phpunit
    services:
      neo4j:
        image: neo4j
        ports:
          - 7687:7687
          - 7474:7474
        env:
          NEO4J_AUTH: none
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"
          --health-interval 1s
          --health-timeout 10s
          --health-retries 20
          --health-start-period 3s
